/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaccia;

import gestioneFile.GestioneFile;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import materiale.AudioVisivo;
import materiale.Libro;
import materiale.MaterialeBiblioteca;
import materiale.MaterialeBiblioteca.tipoMateriale;
import materiale.Rivista;

/**
 *
 * @author lucrezia.pasulo
 */
public class FrameNewMateriale extends javax.swing.JFrame {

    /**
     * Creates new form FrameNewMateriale
     */
    JFrame frameInventario;

    public FrameNewMateriale(JFrame frameInventario) {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        this.frameInventario = frameInventario;

        // ------------
        // Popolo su interfaccia la lista "tipo"
        tipoMateriale[] tmp2 = tipoMateriale.values();
        String[] stringaTmp2 = new String[tmp2.length];

        for (int i = 0; i < tmp2.length; i++) {
            stringaTmp2[i] = tmp2[i].toString();
        }
        jListTipo.setListData(stringaTmp2);
        // ------------
        // Popolo su interfaccia la lista "generi"

        jListTipo.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                if (evt.getClickCount() == 1) {

                    String tipoMateriale = jListTipo.getSelectedValue();

                    switch (tipoMateriale) {
                        case "LIBRO":
                            Libro.genereMateriale[] genereLibro = Libro.genereMateriale.values();
                            String[] stringaTmp = new String[genereLibro.length];

                            for (int i = 0; i < genereLibro.length; i++) {
                                stringaTmp[i] = genereLibro[i].toString();
                            }
                            jListGenere.setListData(stringaTmp);
                            break;

                        case "RIVISTA":
                            Rivista.genereMateriale[] genereRivista = Rivista.genereMateriale.values();
                            String[] stringaTmpRivista = new String[genereRivista.length];

                            for (int i = 0; i < genereRivista.length; i++) {
                                stringaTmpRivista[i] = genereRivista[i].toString();
                            }
                            jListGenere.setListData(stringaTmpRivista);
                            break;
                        case "AUDIOVISIVO":
                            AudioVisivo.genereMateriale[] genereAudioVisivo = AudioVisivo.genereMateriale.values();
                            String[] stringaTmpAudioVisivo = new String[genereAudioVisivo.length];

                            for (int i = 0; i < genereAudioVisivo.length; i++) {
                                stringaTmpAudioVisivo[i] = genereAudioVisivo[i].toString();
                            }
                            jListGenere.setListData(stringaTmpAudioVisivo);
                            break;
                    }

                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtFieldTitolo = new javax.swing.JTextField();
        jTxtFieldAutore = new javax.swing.JTextField();
        jTxtFieldAnno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListGenere = new javax.swing.JList<>();
        jButtonSalva = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListTipo = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Titolo");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setText("Nuovo materiale");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Autore");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Anno");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Genere");

        jTxtFieldTitolo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jTxtFieldAutore.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTxtFieldAutore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFieldAutoreActionPerformed(evt);
            }
        });

        jTxtFieldAnno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTxtFieldAnno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFieldAnnoActionPerformed(evt);
            }
        });

        jScrollPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jScrollPane1.setViewportView(jListGenere);

        jButtonSalva.setBackground(new java.awt.Color(0, 204, 51));
        jButtonSalva.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonSalva.setText("Salva");
        jButtonSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Tipologia");

        jScrollPane2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jListTipo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(jListTipo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtFieldAnno, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtFieldAutore, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtFieldTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jButtonSalva, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtFieldTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtFieldAutore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtFieldAnno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addComponent(jButtonSalva, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtFieldAutoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFieldAutoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFieldAutoreActionPerformed

    private void jTxtFieldAnnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFieldAnnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFieldAnnoActionPerformed

    private void jButtonSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvaActionPerformed
        String titolo = jTxtFieldTitolo.getText();
        String autore = jTxtFieldAutore.getText();
        String annoStr = jTxtFieldAnno.getText();
        String genere = jListGenere.getSelectedValue();
        String tipo = jListTipo.getSelectedValue();

        ArrayList listaDaControllare = new ArrayList<>();
        listaDaControllare.add(titolo);
        listaDaControllare.add(autore);
        listaDaControllare.add(annoStr);
        listaDaControllare.add(genere);
        listaDaControllare.add(tipo);

        boolean esito = Controllo.isVuoto(listaDaControllare);
        int annoTmp = Controllo.isNum(annoStr);

        if (esito && annoTmp != -1) {

            // Salvo il nuovo materiale
            if (tipo.equals("LIBRO")) {
                int anno = annoTmp;

                Libro libroToSave = new Libro();

                libroToSave.anno = anno;
                libroToSave.titolo = titolo;
                libroToSave.autore = autore;
                libroToSave.genere = Libro.genereMateriale.valueOf(genere);
                libroToSave.tipo = MaterialeBiblioteca.tipoMateriale.valueOf(tipo);
                libroToSave.isDisponibile = true;

                GestioneFile.creaLibro(titolo, libroToSave);

            } else if (tipo.equals("RIVISTA")) {
                int anno = annoTmp;

                Rivista rivistaToSave = new Rivista();
                rivistaToSave.anno = anno;
                rivistaToSave.titolo = titolo;
                rivistaToSave.autore = autore;
                rivistaToSave.genere = Rivista.genereMateriale.valueOf(genere);
                rivistaToSave.tipo = MaterialeBiblioteca.tipoMateriale.valueOf(tipo);
                rivistaToSave.isDisponibile = true;

                GestioneFile.creaRivista(titolo, rivistaToSave);

            } else if (tipo.equals("AUDIOVISIVO")) {
                int anno = annoTmp;

                Rivista rivistaToSave = new Rivista();
                rivistaToSave.anno = anno;
                rivistaToSave.titolo = titolo;
                rivistaToSave.autore = autore;
                rivistaToSave.genere = Rivista.genereMateriale.valueOf(genere);
                rivistaToSave.tipo = MaterialeBiblioteca.tipoMateriale.valueOf(tipo);

                GestioneFile.creaRivista(titolo, rivistaToSave);

            } else {
                // Errore
            }

            this.setVisible(false);
            frameInventario.setVisible(true);
            return;
        }
        String testo = "Attenzione, compilare tutti i campi per creare il materiale";
        PopupFrame.alertPopup(testo);
    }//GEN-LAST:event_jButtonSalvaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jListGenere;
    private javax.swing.JList<String> jListTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTxtFieldAnno;
    private javax.swing.JTextField jTxtFieldAutore;
    private javax.swing.JTextField jTxtFieldTitolo;
    // End of variables declaration//GEN-END:variables
}
