/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaccia;

import gestioneFile.GestioneFile;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import materiale.MaterialeBiblioteca;
import materiale.MaterialeBibliotecaOperation;

/**
 *
 * @author lu242
 */
public class FrameRestituzione extends javax.swing.JFrame {

    /**
     * Creates new form FrameRestituzione
     */
    public FrameRestituzione(JFrame frameBiblioteca) {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        // Popolo la jList con i tipi di materiale
        MaterialeBiblioteca.tipoMateriale[] tmp2 = MaterialeBiblioteca.tipoMateriale.values();
        String[] stringaTmp2 = new String[tmp2.length];

        for (int i = 0; i < tmp2.length; i++) {
            stringaTmp2[i] = tmp2[i].toString();
        }
        jListTipo.setListData(stringaTmp2);

        // Popolo la lista dei materiali in base al tipo scelto
        jListTipo.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                if (evt.getClickCount() == 1) {
                    String tipo = jListTipo.getSelectedValue();
                    refreshMateriale(tipo);
                }
            }
        });

        jButtonConferma.addActionListener((ActionEvent e) -> {
            String titoloDaRestituire = jListMateriale.getSelectedValue();
            if (titoloDaRestituire == null) {
                PopupFrame.alertPopup("Attenzione, selezionare un titolo da restituire. Richiesta di restituzione fallita");
                return;
            }
            String tipo = jListTipo.getSelectedValue();

            String statoPrestito = "Richiesta restituzione";

            boolean esito = GestioneFile.spostaFile(titoloDaRestituire, tipo, statoPrestito);

            if (esito) {
                PopupFrame.alertPopup("Richiesta di restituzione andata a buon file");
            } else {
                PopupFrame.alertPopup("Richiesta di restituzione fallita");
            }
            frameBiblioteca.setVisible(true);

            this.dispose();
        });

    }

    private MaterialeBibliotecaOperation operation;

    public void onMaterialeReturn(MaterialeBibliotecaOperation operation) {
        this.operation = operation;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonConferma = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListMateriale = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListTipo = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonConferma.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonConferma.setText("Conferma restituzione");
        jButtonConferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfermaActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jListMateriale);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Attualmente in prestito");

        jScrollPane2.setViewportView(jListTipo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButtonConferma))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonConferma, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfermaActionPerformed

    }//GEN-LAST:event_jButtonConfermaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrameRestituzione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrameRestituzione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrameRestituzione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrameRestituzione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrameRestituzione().setVisible(true);
//            }
//        });
//    }
    private void refreshMateriale(String tipo) {
        String[] listaMaterialeFrame = GestioneFile.cercaFile(tipo, "", "SI"); // Mettendo stringa vuota, prende tutto il contenuto della cartella       
        jListMateriale.setListData(listaMaterialeFrame);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConferma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jListMateriale;
    private javax.swing.JList<String> jListTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
