/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaccia;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import materiale.Libro;
import materiale.MaterialeBiblioteca;
import materiale.MaterialeBiblioteca.genereMateriale;

/**
 *
 * @author lucrezia.pasulo
 */
public class FrameNewMateriale extends javax.swing.JFrame {

    /**
     * Creates new form FrameNewMateriale
     */
    public FrameNewMateriale() {
        initComponents();

        // Popolo su interfaccia la lista "generi"
        genereMateriale[] tmp = genereMateriale.values();
        String[] stringaTmp = new String[tmp.length];

        for (int i = 0; i < tmp.length; i++) {
            stringaTmp[i] = tmp.toString();
        }
        jListGenere.setListData(stringaTmp);

        // Button Actions
        jButtonSalva.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                String titolo = jTxtFieldTitolo.getText();
                String autore = jTxtFieldAutore.getText();
                int anno = Integer.parseInt(jTxtFieldAnno.getText());
                String genere = jListGenere.getSelectedValue();
                String tipo = jListTipo.getSelectedValue();
                
                ArrayList listaDaControllare = new ArrayList<>();
                listaDaControllare.add(titolo);
                listaDaControllare.add(autore);
                listaDaControllare.add(anno);
                listaDaControllare.add(genere);
                listaDaControllare.add(tipo);
                
                
                
                

                // Salvo il nuovo materiale
                if (tipo.equals("Libro")) {
                    Libro libroToSave = new Libro();

                    libroToSave.anno = anno;
                    libroToSave.titolo = titolo;
                    libroToSave.autore = autore;
                    libroToSave.genere = genereMateriale.valueOf(genere);                    
                    
                } else if (tipo.equals("Rivista")) {
                    //TODO: implemento Rivista
                } else if (tipo.equals("Audiovisivo")) {
                    //TODO: implemento Audiovisivo
                } else{
                    // Errore
                }
                
                

                new FrameNewMateriale().setVisible(false);
                new FrameInventario().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtFieldTitolo = new javax.swing.JTextField();
        jTxtFieldAutore = new javax.swing.JTextField();
        jTxtFieldAnno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListGenere = new javax.swing.JList<>();
        jButtonSalva = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListTipo = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Titolo");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setText("Nuovo materiale");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Autore");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Anno");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Genere");

        jTxtFieldTitolo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTxtFieldTitolo.setForeground(new java.awt.Color(153, 153, 153));
        jTxtFieldTitolo.setText("Inserisci titolo");

        jTxtFieldAutore.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTxtFieldAutore.setForeground(new java.awt.Color(153, 153, 153));
        jTxtFieldAutore.setText("Inserisci autore");
        jTxtFieldAutore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFieldAutoreActionPerformed(evt);
            }
        });

        jTxtFieldAnno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTxtFieldAnno.setForeground(new java.awt.Color(153, 153, 153));
        jTxtFieldAnno.setText("Inserisci anno");
        jTxtFieldAnno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFieldAnnoActionPerformed(evt);
            }
        });

        jScrollPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jScrollPane1.setViewportView(jListGenere);

        jButtonSalva.setBackground(new java.awt.Color(0, 204, 51));
        jButtonSalva.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonSalva.setText("Salva");
        jButtonSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Tipologia");

        jScrollPane2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jListTipo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jListTipo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Libro", "Rivista", "Audiovisivo" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListTipo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtFieldAnno, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtFieldAutore, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtFieldTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jButtonSalva, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtFieldTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtFieldAutore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtFieldAnno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addComponent(jButtonSalva, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtFieldAutoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFieldAutoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFieldAutoreActionPerformed

    private void jTxtFieldAnnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFieldAnnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFieldAnnoActionPerformed

    private void jButtonSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameNewMateriale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameNewMateriale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameNewMateriale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameNewMateriale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameNewMateriale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jListGenere;
    private javax.swing.JList<String> jListTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTxtFieldAnno;
    private javax.swing.JTextField jTxtFieldAutore;
    private javax.swing.JTextField jTxtFieldTitolo;
    // End of variables declaration//GEN-END:variables
}
